name: "Deploy to Ionos"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted]
    environment: ${{ github.ref_name }}
    env:
      API_URL: ${{ vars.API_URL }}
      WEB_URL: ${{ vars.WEB_URL }}
      DB_HOST: ${{ vars.DB_HOST }}
      DB_USER: ${{ vars.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ vars.DB_NAME }}
      DB_PORT: ${{ vars.DB_PORT }}
    steps:
      - name: Print env
        run: |
          whoami
          id
          groups
          env | sort
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and deploy
        run: |
          # Stop services
          docker compose down

          # Check network
          docker network inspect easy_state_proxy || docker network create easy_state_proxy

          # Start services
          docker compose up -d --build
